org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.java.installations.auto-detect=false
org.gradle.java.installations.auto-download=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1]
forge_version=47.4.20
forge_version_range=[47,)
java_version_range=[17,)

mod_id=tetraholographicblueprint
mod_name=Tetra Holographic Blueprint
mod_version=1.0.0
mod_group_id=com.pycoder.tetraholographicblueprint
mod_authors=Pycoder
mod_description=Tetra holographic blueprint mod for Minecraft 1.20.1.
mod_license=All Rights Reserved
