modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="mutil"
version="6.3.0"
displayName="mutil"
authors="Mickelus"
description='''A collection of utilities used by mods like tetra.'''

[[dependencies.mutil]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mutil]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
