modLoader="javafml"
loaderVersion="${forge_version_range}"
license="${mod_license}"
showAsResourcePack=false

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="logo.png"
description='''${mod_description}'''
features = { java_version = "${java_version_range}" }
displayTest="MATCH_VERSION"
authors="${mod_authors}"

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="tetra"
mandatory=true
versionRange="[6.9.0,6.10)"
ordering="AFTER"
side="BOTH"
